### ISSUE TITLE
Allow initial mode to be set

### ISSUE THREAD

**Issue by durmuse** [ngneat/edit-in-place#100]
### I'm submitting a

Feature request

### Current behavior

It looks like viewMode is always the default option and it is not possible to start with edit mode initially.

### Expected behavior

Allow initial mode to be programmatically set (either being view or edit mode).

**Comment by sumirolabs** [comment]
I've figured out a workaround using `ViewChild` to get the instance of the `EditableComponent` and call `editMode.set(true)` .

```
import { xxx, ViewChild, AfterViewInit } from '@angular/core';

export class XXX... {
  @ViewChild(EditableComponent) editableComponent!: EditableComponent;

  ngAfterViewInit() {
    this.editableComponent.editMode.set(true);
  }
}
```

**Comment by durmuse** [comment]
The solution above works. There is also a method called displayEditMode which does the same thing.
 this.editableComponent().displayEditMode();

This ticket can be closed now.
