### ISSUE TITLE
Deprecated keyword id when installing package

### ISSUE THREAD

**Issue by catapop84** [ngneat/edit-in-place#11]
### I'm submitting a

Bug report

### Current behavior

In an Angular 12 project when I install the package with `ng add @ngneat/edit-in-place` I receive the following warning:

`"SchematicsEditInPlaceAdd" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.`

No problems at the moment. Just wanted to let you know.

**Comment by geromegrignon** [comment]
Fixed with 1.6.1 version
