### ISSUE TITLE
Add enable/disable mode (for edition)

### ISSUE THREAD

**Issue by baxyz** [ngneat/edit-in-place#12]
### I'm submitting a

Feature request

### Current behavior

You can switch to edit mode in any circumstances.

### Expected behavior

It should be very convenient to block programmatically the edition mode (disable it).

### What is the motivation / use case for changing the behavior?

There is lot of use-cases:
- a request is still running to save the previous change
- a user doesn't have rights on this particular item (in case of a use in item rendering)
- a business constraint
- ...

**Comment by geromegrignon** [comment]
1.6 version was released with this feature.

Keeping this issue open as I can't deploy the new demo right now, related to https://github.com/angular-schule/angular-cli-ghpages/issues/137

**Comment by JohannesHoppe** [comment]
I just published `angular-cli-ghpages@1.0.0-rc.3` to npm! This version supports Angular 13.

**Comment by geromegrignon** [comment]
Awesome @JohannesHoppe, thanks for providing this library to the community!

**Comment by JohannesHoppe** [comment]
My pleasure! 😊

**Comment by geromegrignon** [comment]
new version of the demo deployed 🚀
