### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by vijhhh2** [ngneat/edit-in-place#2]
Please update the package to support Angular 10.
When I am updating the angular application I am getting below error.
y metadata from registry...
                  Package "@ngneat/edit-in-place" has an incompatible peer dependency to "@angular/common" (requires "^8.0.0" (extended), would install "10.1.3").
                  Package "@ngneat/edit-in-place" has an incompatible peer dependency to "@angular/core" (requires "^8.0.0" (extended), would install "10.1.3").

**Comment by NetanelBasal** [comment]
@geromegrignon

**Comment by geromegrignon** [comment]
Thanks for reporting it @vijhhh2.

@NetanelBasal can you deploy a new version of the package?

**Comment by vijhhh2** [comment]
Hi @NetanelBasal 
Can you please release a new version supporting angular 10?  I am not able to update my project because of this peer dependency issue.
Also, I want to thank @geromegrignon  @NetanelBasal  for giving this awesome library to the Angular community.

**Comment by NetanelBasal** [comment]
@geromegrignon

**Comment by geromegrignon** [comment]
Hello @vijhhh2 i published a new version to support angular 10 (and the latest one supports angular 11)
