### ISSUE TITLE
Single click event for open/close binding event doesn't get triggered when clicking editableOnSave or editableCancel directives

### ISSUE THREAD

**Issue by ecolman** [ngneat/edit-in-place#3]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using the `click` event for `openBindingEvent` and `closeBindingEvent` along with the `editableOnSave` and `editableCancel` directives, the mode won't switch to `view` when clicking the `editableOnSave` or `editableCancel` elements.

## Expected behavior

When using a single click for the open/close binding event and the `editableOnSave` or `editableCancel` directives, clicking an element using the directives (ie: button) should trigger a `closeBindingEvent` (if using the `click` event) in addition to calling a method.

## Minimal reproduction of the problem with instructions

Update [playground](https://github.com/ngneat/edit-in-place/blob/master/src/app/app.component.ts#L18) to use `click` for `openBindingEvent`, then try `Sample input with action buttons`, by clicking into it for edit mode, then using the buttons to try to change the mode back to view.

## What is the motivation / use case for changing the behavior?

To allow for a simple click to change mode and then to use the save or cancel buttons or a click outside element to change back to view mode.

## Environment

<pre><code>
Angular version: 10.1.3

Browser:
- [ X] Chrome (desktop) version 86.0.4240.198
 
For Tooling issues:
- Node version: 12.16.1
- Platform:  Windows

</code></pre>

**Comment by geromegrignon** [comment]
Thanks for pointing it out.

I'll work on a fix today.

**Comment by geromegrignon** [comment]
It's fixed in @ngneat/edit-in-place@1.2.0

**Comment by ecolman** [comment]
Just gave this a test, and it works great the first switch from view to edit and back to view with the cancel button.  The second time I do it though, the mode doesn't switch back to view.

Reproduce: Use `click` for `openBindingEvent` on `Sample input with action buttons`.  Click into `foo` to go into edit mode, change value to `foo1` and hit cancel button.  Then click into `foo` again, change to `foo1` and hit the cancel button again.  It will reset the value, but not switch the mode to view.

**Comment by geromegrignon** [comment]
@ecolman Thanks for the feedback, i made a new fixe with @ngneat/edit-in-place@1.3.0

**Comment by ecolman** [comment]
@geromegrignon Works perfectly.  Thank you for this!
