### ISSUE TITLE
Feature Request: EditableComponent editableModeChange() event.

### ISSUE THREAD

**Issue by cesaric** [ngneat/edit-in-place#4]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

Would it be possible to incorporate an `editableModeChange()` event on the EditableComponent?  Or possibly an `onEdit()` or `onView()` event if it conflicts with the EditableGroupDirective?

There's some simple use cases such as opening a dropdown automatically on edit-mode that would be convenient.  I attempted tying into the `editMode$` observable but that gets fired multiple times.

**Comment by geromegrignon** [comment]
Thanks for pointing it out.

I'll create a `modeChange()` event.
As it's used on the *EditableComponent* there is no need to prefix it with *editable*.
Then there should be no conflict with existing `editableModeChange ()`.

**Comment by geromegrignon** [comment]
This feature is now available in @ngneat/edit-in-place@1.2.0
