### ISSUE TITLE
Editable inside EditableGroup goes into edit mode without using button after first use

### ISSUE THREAD

**Issue by laurentchicoine** [ngneat/edit-in-place#6]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

On first load of an editableGroup, clicking on the contained editables does not trigger edit mode.
After going into edit mode using a defined button and then going back in view mode, clicking on the contained editables trigger the edit mode for the target editable

## Expected behavior

Clicking on editables inside an editableGroup never trigger the edit mode.

## Minimal reproduction of the problem with instructions

I was not able to reproduce on the demo page (is it running the latest release 1.3.0?)
1) Install latest release (git clone and npm install)
2) ng serve
3) Open the demo page on localhost
4) In the Grouped inputs example, click on Edit
5) Click on cancel
6) Click on John Doe

## Environment

<pre><code>
Angular version: 11.0.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by geromegrignon** [comment]
Thanks for reporting it.
There is indeed a regression.
I'll take a look at it today.

**Comment by geromegrignon** [comment]
@laurentchicoine It's now fixed with  @ngneat/edit-in-place@1.3.1
I updated the demo too to match the current version.
