### ISSUE TITLE
Programmatically trigger Edit and View mode

### ISSUE THREAD

**Issue by Rajdeep97** [ngneat/edit-in-place#63]
### I'm submitting a

Feature request

### Current behavior

There's no way to trigger Edit & View mode programmatically. This would be a helpful feature

### Expected behavior

An @Input() directive for both Edit as well as View mode activation.

### Minimal reproduction of the problem with instructions

-

### What is the motivation / use case for changing the behavior?

Being able to trigger the View mode and Edit mode programmatically would be a great addition. Can be used in a lot of scenarios where we want some outside event to trigger the respective modes.

**Comment by bncunha** [comment]
You could take a component reference with "@Viewchild" and use functions `displayEditMode()` and `cancelEdit()` to toggle modes.

**Comment by Rajdeep97** [comment]
Thanks @bncunha
