### ISSUE TITLE
Ability to access classes?

### ISSUE THREAD

**Issue by chasestory** [ngneat/edit-in-place#9]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Unable to change style of the component view mode.

## Expected behavior
 the ability to change/update styles with accessing classes/ for making it look like a link - or any use case required to fit needs.

## Minimal reproduction of the problem with instructions
Attempt to style viewMode 

## What is the motivation / use case for changing the behavior?

My instance is making a header for a form editable. However, the requirements necessary want it underlined to show it can be edited, with an indicator to the right of the object, simple and straight forward, but I cannot simply make this happen at this time...  

Angular version: 11.0.6

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.0
- Platform:  Mac 

Others:

Example: 
![](https://user-images.githubusercontent.com/25908846/118150675-0b5ac680-b3d0-11eb-9922-4636701ca9e1.png?raw=true)

**Comment by geromegrignon** [comment]
Hello,

The library provide placeholders for your components, focusing on the way to display them according to the actual mode (viewMode/editMode).

As you are the one providing the html content for each of these modes, you have full control to style them.
Here is an example by adding a dashed border bottom on the component projected into the viewMode : https://stackblitz.com/edit/github-xxddna?file=src%2Fapp%2Fapp.component.html

**Comment by chasestory** [comment]
@geromegrignon  thank you so much, you are a life saver!
