### ISSUE TITLE
Updating from v1.6.1 to 1.9.0 can't import import {EditableModule} from "@ngneat/edit-in-place";

### ISSUE THREAD

**Issue by catapop84** [ngneat/edit-in-place#95]
### I'm submitting a

Regression (a behavior that used to work and stopped working in a new release)

### Current behavior

In 1.6.1 everything is working great.
in 1.9.0 `import {EditableModule} from "@ngneat/edit-in-place";` throws error that it can't import the module `TS2305: Module  "@ngneat/edit-in-place"  has no exported member  EditableModule`

**Comment by geromegrignon** [comment]
resolved.
