### ISSUE TITLE
Focus and default value

### ISSUE THREAD

**Issue by antiftw** [ngneat/edit-in-place#99]
### I'm submitting a

Support request

### Current behavior

I'm having two issues/questions:

- One regarding the focus of the input fields, both the focussing on editMode, and the blurring when switching back to viewMode.
- Second, making it so that the input field has a default value filled in when switching to editMode (The regular value property of the input field does not have an effect weirdly enough)

Regarding the first issue, I'm not sure what the expected behaviour should be? Because it seems quite obvious that it should focus on the input field you have just switched to?

I've set the editableFocusable (since that seems related, however its not really clear how this would work exactly), I've tried manually focusing using (modeChange)="", but to no avail.

Thanks in advance.

### Minimal reproduction of the problem with instructions

```html
<editable (modeChange)="focus($event, 'fieldName')">
  <ng-template viewMode>fieldValue</ng-template>
  <ng-template editMode>
    <input
      editableOnEnter
      editableOnEscape
      editableFocusable
      [formControl]="this.fieldControl"
      value="fieldValue" />
  </ng-template>
</editable>
```

### Environment

```shell
Angular 17.0.6
Ionic 7.1.5
```

**Comment by geromegrignon** [comment]
Hello,

About the first question, it would indeed be a great user experience improvement to focus on the switch from viewMode to editMode if that's the question.

About the second question, that's about Angular, not this library.
You can't use `value='fieldValue` with Reactive Forms to expect an initial value. Do it on form initialization or with `setValue/patchValue`functions.

**Comment by antiftw** [comment]
1) Hi, yes that was indeed what I meant for the first question. Do I understand correctly from your answer that this is not yet available functionality?

2) Okay did not know that, I will look into that.

3) Okay, removed them

Thanks for the quick response and tips!

**Comment by antiftw** [comment]
1) Managed to get a focus working using the modeChange. The solution is pretty straightforward. The issue was that it needed the setTimeout for it to work, even if it's with 0 delay.

```html
<editable
  (save)="update(aboutControl, 'about')"
  (modeChange)="focus($event, 'about')">
  <ng-template viewMode>
    {{ model.about }}
    <ion-icon class="edit" name="pencil"></ion-icon>
  </ng-template>
  <ng-template editMode>
    <input
      id="about"
      type="textarea"
      editableOnEnter
      editableOnEscape
      editableFocusable
      (keyup.enter)="update(aboutControl, 'about')"
      [formControl]="aboutControl" />
  </ng-template>
</editable>
```

```typescript
  focus(event$: string, field: string) {
    setTimeout(() => {
      // Focus on selected field when in edit mode.
      if (event$ === 'edit') {
        document.getElementById(field)?.focus();
      }
    }, 0);
  }
```

2. Also managed  to get the default value working using the FormController constructor thanks to your tip.
